M48
; DRILL file {KiCad 6.0.9-8da3e8f707~116~ubuntu20.04.1} date Sun Mar 26 14:19:45 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-03-26T14:19:45+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.9-8da3e8f707~116~ubuntu20.04.1
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C1.520
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X9.92Y-13.5
X15.0Y-13.5
T2
X3.5Y-14.0
X21.5Y-14.0
T0
M30
